service: toucanny
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs16.x

functions:
    api:
        handler: index.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
